prevent CI to run twice in releases, but pushing empty commits with tags won't trigger a release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,11 +7,7 @@ defaults:
     shell: bash -ieo pipefail {0}
 
 on:
-  push:
-    tags:
-      - 'v*' # Push events matching v*, i.e. v0.0.2, v1, etc.
-
-  # Can be triggered by other workflows
+  # Can be triggered only by other workflows
   workflow_call:
     inputs:
       release_version:
@@ -21,23 +17,14 @@ on:
 
 jobs:
 
-  # Call CI
-  ci-check:
-    uses: ./.github/workflows/ci.yml
-    secrets: inherit
-    with:
-      # Crawler tests are skipped if the workflow was triggered by another workflow
-      skip_crawler_test: ${{ inputs.release_version != '' && true ||  false  }}
-
   create-release:
     runs-on: ubuntu-latest
-    needs: ci-check
 
     steps:
-      - name: Checkout code
+      - name: Checkout code 📥
         uses: actions/checkout@v2
 
-      - name: Set Release version
+      - name: Set Release version 🏷️
         shell: bash
         run: |
           EVENT=${{ github.event_name }}
@@ -48,12 +35,15 @@ jobs:
             if [[ $EVENT == "workflow_call" ]]; then
               echo "[ERROR] RELEASE_VERSION is '$RELEASE_VERSION' and it's invalid for a workflow_call";
               exit 1;
-            else
+            elif [[ ${{ github.ref_name }} =~ v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+ ]]; then
               echo "RELEASE_VERSION=$(echo ${{ github.ref_name }} | cut -c 2-)" >> $GITHUB_ENV
+            else
+              echo "[ERROR] github.ref_name is '${{ github.ref_name }}' and it's invalid for creating a release"
+              exit 1;
             fi
           fi
 
-      - name: Create Release
+      - name: Create Release 📦
         id: create_release
         uses: actions/create-release@v1
         env:
@@ -69,12 +59,13 @@ jobs:
     needs: create-release
     
     steps:
-    - name: Checkout
+    - name: Checkout code 📥
       uses: actions/checkout@v2
       with:
         ref: ${{ github.ref }}
-
-    - uses: actions/setup-node@v3
+      
+    - name: NodeJS setup 🛠️
+      uses: actions/setup-node@v3
       with:
         node-version: 18
         registry-url: 'https://registry.npmjs.org'
@@ -82,7 +73,7 @@ jobs:
     - name: Install dependencies and build 🔧
       run: npm ci && npm run build && npm run pack
 
-    - name: Publish package on NPM 📦
+    - name: Publish package on NPM 🚀
       run: npm run pub
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
