check github events and inputs prior to release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -37,10 +37,17 @@ jobs:
       - name: Set Release version
         shell: bash
         run: |
-          if [[ -n ${{ github.event.inputs.release_version }} ]]; then
-            echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV
+          EVENT=${{ github.event_name }}
+          RELEASE_VERSION=${{ github.event.inputs.release_version }}
+          if [[ -n $RELEASE_VERSION ]]; then
+            echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
           else
-            echo "RELEASE_VERSION=$(echo ${{ github.ref_name }} | cut -c 2-)" >> $GITHUB_ENV
+            if [[ $EVENT == "workflow_call" ]]; then
+              echo "[ERROR] RELEASE_VERSION is '$RELEASE_VERSION' and it's invalid for a workflow_call";
+              exit 1;
+            else
+              echo "RELEASE_VERSION=$(echo ${{ github.ref_name }} | cut -c 2-)" >> $GITHUB_ENV
+            fi
           fi
 
       - name: Create Release
